version: "3"

services:
    client:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./src:/usr/share/nginx/html
            - ./conf/nginx.conf:/etc/nginx/nginx.conf